const squareData = [
  { title: "Roy ‘Chubby’ Brown" },
  { title: "Tantadrip Foundation" },
  { title: "Non sequitur" },
  { title: "Stockport" },
  { title: "“___? I gatchu!”" },
  { title: "King Cactus Cam" },
  { title: "Soul laughs at accent" },
  { title: "“Tantacrul is typing…”" },
  { title: "*VC Renamed*" },
  { title: "Water Ship down" },
  { title: "Marz Cat Cam" },
  { title: "SHIP’S CLOCK" },
  { title: "Bad Pun" },
  { title: "“Advanced”" },
  { title: "Gilroy" },
  { title: "Star Wars" },
  { title: "P4rp server muted" },
  { title: "Soul’s Twitter" },
  { title: "Lara Dog Cam" },
  { title: "Audacity Controversy" },
  { title: "Tanta’s kids make him leave" },
  { title: "Important Videos" },
  { title: "Formula One" },
  { title: "“What is (Item on bingo card)?”" },
  { title: "Putin’s bitch" },
  { title: "Tantakind" },
  { title: "X af" },
  { title: "“Fuck’s sake Soul”" },
  { title: "Linus Boman" },
  { title: "Bullying Americans" },
  { title: "*Soul Draws*" },
  { title: "Mourn Hall of Jank" },
  { title: "“Hey it’s Tantacrul!”" },
  { title: "Sudden Serious Topic" },
  { title: "Simon" },
  { title: "Calliopean club" },
  { title: "Mop’s US Road trip" },
  { title: "Ben Shapiro" },
  { title: "Microsoft" },
  { title: "Post Punk Podge" },
  { title: "*Soul Wheeze*" },
  { title: "Feldman’s Yeast" },
  { title: "Politics" },
  { title: "“You’re 12”" },
  { title: "“X is getting worse!”" },
  { title: "Fred_Durst.jpeg" },
  { title: "Eurovision" },
  { title: "Einaudi" },
  { title: "“One at a time, please”" },
];

export default squareData;
